### ISSUE TITLE
Can not build on latest Yocto 

### ISSUE THREAD

**Issue by nschle85** [Tragetaschen/meta-aspnet#8]
I am trying to build .NET Core for Yocto. I am getting the following problem:
CMake Error at /home/nschle85/GIT-YOCTO/poky/build/tmp/work/core2-64-poky-linux/coreclr/2.0.0-r0/recipe-sysroot-native/usr/share/cmake-3.10/Modules/CMakeDetermineSystem.cmake:100 (message):
|   Could not find toolchain file:
|   /home/nschle85/GIT-YOCTO/poky/build/tmp/work/core2-64-poky-linux/coreclr/2.0.0-r0/git/cross/x64/toolchain.cmak

**Comment by Tragetaschen** [comment]
I have only ever tested cross-compiling for ARM and looking through the recipe, it's [quite obvious](https://github.com/Tragetaschen/meta-aspnet/blob/master/recipes-dotnet/corehost/coreclr.inc#L34) that x64 is guaranteed to fail later in the build.
From the CoreCLR sources, it seems that cross-compilation for x64 is handled quite differently (if at all) from the way it's done for ARM or ARM64. I haven't looked into how to make that work. I would definitely appreciate any PRs that prepare the recipe for a non-ARM target!


There's only one caveat: .NET Core 2.1 is going to be released very soon and with it, there's a new approach to building from source: https://github.com/dotnet/source-build. I'll go into that direction once I have some spare time, so the question is how much effort should be put into fixing the 2.0 build.

**Comment by nschle85** [comment]
Thank you for the fast response, in my opinion you should not try to fix the 2.0 build.

**Comment by nschle85** [comment]
I will close this defect: "won't be fixed"
