### ISSUE TITLE
Problems building for aarch64

### ISSUE THREAD

**Issue by erlenfas** [Tragetaschen/meta-aspnet#9]
Hi,

I am trying to get .NET working for an iMX8 module, using NXP's morty release. I am very new to the Yocto/Linux concept, so please excuse my lack of competence.. 

If I understand it correctly, the .NET build should work for arch64. Please correct me if I am wrong at this point. Sitting at a Ubuntu 16.04. The fail occurs during coreclr build:

```
| Running: /home/parallels/var-imx8m-yocto-morty/build_xwayland/tmp/work/aarch64-poky-linux/coreclr/2.0.0-r0/git/Tools/dotnetcli/dotnet /home/parallels/var-imx8m-yocto-morty/build_xwayland/tmp/work/aarch64-poky-linux/coreclr/2.0.0-r0/git/Tools/run.exe /home/parallels/var-imx8m-yocto-morty/build_xwayland/tmp/work/aarch64-poky-linux/coreclr/2.0.0-r0/git/config.json build -Project=/home/parallels/var-imx8m-yocto-morty/build_xwayland/tmp/work/aarch64-poky-linux/coreclr/2.0.0-r0/git/build.proj -generateHeaderUnix -NativeVersionSourceFile=/home/parallels/var-imx8m-yocto-morty/build_xwayland/tmp/work/aarch64-poky-linux/coreclr/2.0.0-r0/git/bin/obj/Linux.x64.Release/version.cpp -BuildArch=x64 -BuildType=Release -BuildOS=Linux aarch64
| Error: Parameter not recognized: aarch64.
```

Is this expected or an error?

**Comment by Tragetaschen** [comment]
I never had the chance to build for aarch64, but by looking through the CoreCLR repository, I'd guess that it expects `arm64` instead of `aarch64` as architecture parameter. You could try hardcoding that into the recipe for testing purposes.

However, there isn't yet any .NET Core release with official support for aarch64/arm64 (https://blogs.msdn.microsoft.com/dotnet/2018/05/30/announcing-net-core-2-1/#comment-543755).
For 2.0 (which is what this layer currently builds), there hasn't been any official ARM story and for 2.1, only 32-Bit ARM made it into the release.

**Comment by erlenfas** [comment]
Thanks a lot for the quick response, and the explanation (and in general, the efforts put down into the repo). I tried hardcoding it only to be stuck at a later stage in the build, but I will try to investigate it further when I have some time. Also thanks for the clarification of official support - I hope the support for arm64 will be included in a later stage of development of .NET core. I am currently investigating if Yocto may be a viable solution for running a large codebase of C#, previously running on WIN CE 7.

**Comment by Tragetaschen** [comment]
arm64 is definitely on their road map and considerable amount of work went into it already.

For your evaluation: Keep in mind that (albeit there being a strong wish for it from the community), there are no plans for a cross-platform graphics stack story directly in .NET Core. There's always Mono for running a .NET application on Linux and I'm currently using it for a combination of ASP.NET Core web server process and HTML5, web-browser-hosted GUI.

**Comment by erlenfas** [comment]
That's good news for our codebase. 

Yes, the GUI part is a clear limitation. Although the WIN CE platform is no longer updated, it has proved convenient using a single instance of a Visual Studio project for both GUI and backend, appreciated by the developers. We are looking into either a similar solution as you describe, using HTML 5, or maybe going down the Qt path. The GUI will need to be rewritten in any case, so finding best tools for the job is the main task.
